---
title: "Geocoding from UC Davis Pavillion"
author: Last updated, `r format(Sys.Date(), "%B %d, %Y")`

output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    theme: readable
    social: menu
    source_code: embed
runtime: shiny
---

```{r,inlcude=FALSE,warning=FALSE,message=FALSE, warning=FALSE, r,inlcude=FALSE}
knitr::opts_chunk$set(echo = T)
knitr::opts_chunk$set(message = F)
knitr::opts_chunk$set(warning = F)
library(ggplot2)
library(tidyverse)
library(plotly)
#install.packages('devtools')
#devtools::install_github("michaeldorman/mapsapi")
#devtools::install_github("dkahle/ggmap")
library(mapsapi)
library(ggmap)
library(maps)
library(mapproj)
library(leaflet)
library(shiny)
library(rsconnect)
library(dplyr)
library(astsa)
library(tseries)
library(zoo)
require(graphics)
library(forecast)
library(lubridate)
library(TSstudio)
```



Sidebar {.sidebar data-width=400}
======================================================================

```{r, echo=FALSE}

    # getwd() = "/Users/christopherton/Documents/HackDavis20"
    fileInput("file", "Choose a CSV File",  multiple = TRUE, accept = c("text/csv",
                               "text/comma-separated-values,text/plain", ".csv"))
      
    helpText("Upload a .csv of usage results for one building. Your file should have a column named   \"Date       Time\", \"Chilled Water\", and \"Electricity Steam\".")
      
    #Input: Select number of rows to display ----
    radioButtons("disp", "Display",
                  choices = c(Head = "head",
                                 All = "all"),
                  selected = "head")
    
    actionButton("recalc", "GO")
    p()
    

```

```{r,echo=FALSE}
renderTable({
  
  req(input$file)
  usage <- read.csv(input$file$datapath)
  
  if(input$disp == "head"){
    return(head(usage))
  }else{
    return(usage)
  }
})
```



Analysis
============================================================================

Row {data-height=700}
-----------------------------------------------------------------------

```{r,include=FALSE,message=FALSE, warning=FALSE}
api_key = "AIzaSyAnaLkG1iw1J1cTlAR6ZGGhF1bS5C7968Q"
register_google(key = api_key)
```


### Forecast Visualization

```{r, echo=FALSE}

renderPlotly({
    
      req(input$file)
  
      #usage <- read_csv("tupper_usage_1-18-2020.csv")
      usage <- read_csv(input$file$datapath)
      
      usage$`Date Time`<-as.Date(usage$`Date Time`,'%m/%d/%Y')
      invisible(as.Date(usage$`Date Time`,format))
      
      usage <- usage[c(1:36),]
      #usage$Electricity[13] = 2309361
      usage$total <-  usage$`Chilled Water` + usage$Electricity + usage$Steam
      #usage_copy <- usage
      usage <- usage[,-c(2,3,4)]
      names(usage) <- c('Date','Total_Usage')
      usage$Date <- rev(usage$Date)
      
      ################################################################################################
      ggplotly(
        ggplot(usage,aes(x=usage$Date,y=usage$Total_Usage)) +
          geom_point() +
          geom_line()+
          labs(x = "Date",
            y = "Total Usage (kbut)",
            title = "Montly Usage Data")
      )%>% 
              rangeslider(start = min(as.numeric(usage$Date)), 
                          end = max(as.numeric(usage$Date)))
})
    
```



### What's Going On?

```{r,echo=FALSE}

  

plot.acf.pacf <- function(s)
{
  #par(mfrow=c(2,1))
  #tsplot(s,col=4,xlab = "Months",ylab="Usage",main="Monthly Energy Usage")
  #abline(reg=lm(s~time(s)))
  #lines(ksmooth(time(s), s, "normal", bandwidth = 3), lwd=2, col=2)

  
  par(mfrow=c(2,2))
  acf(s,lag.max = 120)
  pacf(s,lag.max = 120)

  
  qqnorm(s, pch = 1, frame = FALSE)
  qqline(s, col = "steelblue", lwd = 2)
  
}

plot.acf.pacf(usage$Total_Usage)


#Test the null hypothesis that the log of the series has a unit root, versus the alternate hypothesis that the process is stationary. 
# Want a p-value of less than 0.05 (or smaller)

test_stationarity <- function(dat)
{
  adf.test(dat)
}
```


```{r,warning=FALSE}



sta = test_stationarity(usage$Total_Usage)

i = sta$p.value
while(i > 0.05){ #0.05 or less is the p-value needed for stationarity
  print(i)
  i = test_stationarity(diff(usage$Total_Usage))$p.value
  print(i)
}

#now stationary, meaning no trend
#but the expected value for the same month for different years may be the same
```


```{r}

#assuming seasonality exists regardless of building, applying differencing of lag 12
auto = auto.arima(usage$Total_Usage,trace=TRUE)




```


```{r,echo=FALSE}

```








